### ISSUE TITLE
ASql setNumericalPrecisionPolicy 

### ISSUE THREAD

**Issue by mike23456** [cutelyst/asql#7]
Is there an equivalent of (setNumericalPrecisionPolicy) in ASql?

//pseudo code 
QSqlQuery q();
q.setNumericalPrecisionPolicy(QSql::HighPrecision);

we use the above to return  columns  having "numeric" data type in the database  as TEXT cuz we want to keep high precision (16 decimal places and in some cases 50 decimals). We are using types from the boost arbitrary precision library to store and handle the values in  C++  instead of using the native double type.

**Comment by dantti** [comment]
QtSql converts all binded values to text before sending which is why that option exists in the first place, you can send your numeric as text QString and do the cast server side like:

    $1::numeric(2,50)

When retrieving the number using AColumn::toString() will just extract the data as text, and maybe you need to also cast it server side like:

    123.435454545454545::text
